services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    networks:
      - caddy
    restart: unless-stopped
  drawdb:
    build: .
    container_name: drawdb
    expose:
      - 4582
    labels: 
      caddy: "http://drawdb.localhost"
      caddy.reverse_proxy: "{{upstreams 4582}}"
      caddy.basic_auth: /*
      caddy.basic_auth.admin: "$2y$05$7rdEwDLvUgt9H7dAU1UKI.W9DkHX/6G.S2xKjduQg2yNNv.inUfsO"
    networks:
      - caddy

  
networks:
  caddy:

volumes:
  caddy_data:
  caddy_config:
